server:
  port: 8083
redis:
  servers: ip104:7001 ip104:7002 ip105:7001
  databases: 4
  maxAttempts: 2
  maxTotal: 1024
  maxIdle: 1024
  minIdle: 32
  timeout: 100
  soTimeout: 200
  maxWaitMillis: 300
  appName: util_demo
  scanShortNameBasePackage: com.demo.tools # 简称类的位置
rateLimit:
  redis:
    algorithm: token
  java:
    algorithm: token